name: quiz_flutter
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  #ASSET
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  google_fonts: ^5.1.0
  #INTL
  intl_utils: ^2.8.4
  #STATE MANAGERMENT
  provider: ^6.0.5
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  #GOOGLE NAV
  google_nav_bar: ^5.0.6
  #SHARED PREFERENCES
  shared_preferences: ^2.2.0
  #DOT INDICATOR
  dots_indicator: ^3.0.0
  #TOAST
  fluttertoast: ^8.2.2
  #FIREBASE
  firebase_core: ^2.15.1
  firebase_auth: ^4.8.0
  #FLOW BUILDER
  flow_builder: ^0.0.9
  cloud_firestore: ^4.9.0
  flutter_svg_provider: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - lib/res/images/
    - lib/res/icons/
  uses-material-design: true
  generate: true

flutter_intl:
  enabled: true
